### ISSUE TITLE
Error: Cannot find module 'process/browser.js'

### ISSUE THREAD

**Issue by MichailShcherbakov** [davidmyersdev/vite-plugin-node-polyfills#32]
Hi @davidmyersdev. 

When I run `yarn`  I get a waring 

![Screenshot_2](https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/50011226/ee57423e-e7f9-48b7-8be9-cbf8179093d4)

And when I try to build a lib `vite` throws an error

![Screenshot_3](https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/50011226/e7ae3788-0e9b-4b16-b74c-f2c4fca344a6)

[Link to Codesandbox](https://codesandbox.io/p/sandbox/lively-glitter-fl8jf3?file=%2F.codesandbox%2FDockerfile%3A1%2C13)

Can you help me to fix it? 

Thank you!

**Comment by manylovv** [comment]
I've got the same error

**Comment by manylovv** [comment]
I decided to try another version, and ^0.7.0 works just fine for me

**Comment by MichailShcherbakov** [comment]
@manylovv Unfortunately, I can't use 0.7.0 version in my project. I need "exclude" functionality.

It looks like the error is in `"buffer-polyfill"` in the `package.json`. Yarn possibly does not support it.

I don't know why the `shim.js' file is used here
```ts
const globalShimsPath = require.resolve('vite-plugin-node-polyfills/shims')
```

instead of using the `helpers/esbuild/shim.js` file from `node-stdlib-browser`

```ts
const globalShimsPath = require.resolve('node-stdlib-browser/helpers/esbuild/shim')
```

and for what this one

```ts
included[name] = globals.includes(name) ? globalShimsPath : value
```

I just changed all of it. And it works fine for me.

**Comment by davidmyersdev** [comment]
I've started looking into this, but I'm having trouble reproducing it locally.

**Comment by MichailShcherbakov** [comment]
@davidmyersdev I've attached a link to an [example project](https://codesandbox.io/p/sandbox/lively-glitter-fl8jf3). The error is reproduced when building or running project after `yarn install`.

**Comment by davidmyersdev** [comment]
I think I see what's happening now. It appears that Yarn v1 does not handle the aliased `process` dependency as it should, so it just skips it rather than unpack it into `node_modules`. I'll have to figure out how I want to handle this, but it shouldn't be too bad to get a fix together. To answer your earlier question, the replacement shims file is necessary because `node-stdlib-browser` has an out-of-date `buffer` dependency.

**Comment by davidmyersdev** [comment]
There also appears to be an open issue about this bug without any responses.
https://github.com/yarnpkg/yarn/issues/6907

**Comment by davidmyersdev** [comment]
This is fixed in `v0.11.3`.

**Comment by martonlederer** [comment]
Thank you @davidmyersdev

**Comment by AlexanderArce** [comment]
It's still happening in the example supplied by @MichailShcherbakov 

> @davidmyersdev I've attached a link to an [example project](https://codesandbox.io/p/sandbox/lively-glitter-fl8jf3). The error is reproduced when building or running project after `yarn install`.

And is still happening to me with version 0.11.3.

Maybe the issue is with yarn? I am using version 1.22.19 of yarn.
