### ISSUE TITLE
Requiring node core module with trailing slash `/` ERROR

### ISSUE THREAD

**Issue by paro-paro** [davidmyersdev/vite-plugin-node-polyfills#67]
@davidmyersdev 

My original post [here](https://github.com/davidmyersdev/vite-plugin-node-polyfills/issues/41#issuecomment-1869660864)

As pointed in the previous thread, seems like the plugin fails due to an upstream dependency trying to import `process/` instead of `process`.

Doing some digging I detected that the conflicting dependency was `readable-stream` which is a NodeJS official package. Looks like the trailing slash `/` syntax is intended... as explained [here](https://github.com/nodejs/readable-stream/issues/526).

Do not really understand the rationale behind it since it feels like a workaround for browserify...

In any case, it would be great if we can expect a fix from the plugin side.

Thanks a lot for your help!

**Comment by davidmyersdev** [comment]
Repro: https://stackblitz.com/edit/github-yd3jt3?file=nuxt.config.ts

**Comment by davidmyersdev** [comment]
This is fixed in [`v0.19.0`](https://github.com/davidmyersdev/vite-plugin-node-polyfills/releases/tag/v0.19.0).

Updated repro: https://stackblitz.com/edit/github-yd3jt3-9mmv9s?file=package.json

**Comment by paro-paro** [comment]
Hi @davidmyersdev 

Thanks a lot for the quick fix. The trailing slash issue is indeed fixed in the new version. However, the nuxt production build is still failing for me with a different error from #41. 

Now, the `exports` object is injected in the final bundle, making the app crash on production. 

Reproduction: https://stackblitz.com/edit/github-yd3jt3?file=nuxt.config.ts 

1. Better to download it and test it locally.
2. Running `nuxt build` and `nuxt preview` will return an "exports is not defined" error.

The reproduction uses nuxt 3.8.2 (which is the version I am currently using) but I have also tested the latest 3.9.0 release (which levarages vite 5.x) and no luck either.

Let me know if I could expect any help from the plugin side. 

Thanks in advanced!

**Comment by pi0** [comment]
@davidmyersdev I would be more than happy to help if you like to migrate the polyfill backend to unenv, it should make the plugin much more usable.
